const { JSDOM } = require('jsdom');
const fs = require('fs');
const assert = require('assert/strict');
const root = require('path').resolve(__dirname, '..');
const dom = new JSDOM(fs.readFileSync(root + '/index.html', 'utf8'), { url: 'https://jesuschristsavestoken.com/', runScripts: 'outside-only', pretendToBeVisual: true });
const w = dom.window, d = w.document;
let clock = 1790000000000, requests = 0, referenceAvailable = true;
w.Date.now = () => clock;
w.matchMedia = () => ({ matches: false });
const intervals = [];
w.setInterval = (fn, ms) => { intervals.push({ fn, ms }); return intervals.length; };
w.fetch = async () => { requests++; if (!referenceAvailable) throw new Error('offline'); return { ok: true, json: async () => ({ ripple: { usd: 1, last_updated_at: clock / 1000 }, bitcoin: { usd: 60000, last_updated_at: clock / 1000 } }) }; };
w.__jcsXrplRequest = async () => ({ result: { validated: true, ledger_index: 100, obligations: { JCS: '1000000' } } });
const text = id => d.getElementById(id)?.textContent;
w.eval(fs.readFileSync(root + '/js/jcs-market.js', 'utf8'));
const tick = async () => { await new Promise(resolve => setImmediate(resolve)); await new Promise(resolve => setImmediate(resolve)); };
const snapshot = async (overrides = {}) => { w.dispatchEvent(new w.CustomEvent('jcs:market-snapshot', { detail: { validated: true, ledgerIndex: 100, observedAt: clock, priceXrpPerJcs: 0.000123, ...overrides } })); await tick(); };
(async () => {
  await snapshot();
  assert.equal(text('jcsProjectPrice'), '$0.000123');
  assert.match(text('jcsChartStatus'), /1 observation/);
  assert.equal(d.querySelector('#jcsComparisonChart svg'), null);
  await snapshot();
  assert.equal(requests, 1, 'Repeated same-minute snapshot must reuse external reference');
  clock += 60000;
  await snapshot({ priceXrpPerJcs: 0.000124 });
  assert.equal(d.querySelectorAll('#jcsComparisonChart svg path').length, 3);
  assert.equal(d.querySelector('#comparisonObservation').max, '1');
  assert.match(text('jcsChartStatus'), /2 observations/);
  const before = text('jcsProjectPrice');
  await snapshot({ observedAt: clock - 100000, priceXrpPerJcs: 5000 });
  assert.equal(text('jcsProjectPrice'), before, 'Stale ledger event must be rejected');
  await snapshot({ validated: false, priceXrpPerJcs: 5000 });
  assert.equal(text('jcsProjectPrice'), before, 'Unvalidated event must be rejected');
  referenceAvailable = false;
  clock += 181000;
  await snapshot({ priceXrpPerJcs: 0.000125 });
  assert.equal(text('jcsProjectPrice'), '0.000125 XRP');
  assert.match(text('jcsChartStatus'), /USD comparison unavailable/);
  assert.equal(d.querySelector('#comparisonObservation').max, '1', 'Stale provider price must not create a chart point');
  clock += 100000;
  intervals.forEach(({ fn }) => fn());
  assert.match(text('jcsProjectChange'), /waiting to reconnect/);
  assert.match(text('jcsChartStatus'), /Updates paused/);
  assert(intervals.every(x => x.ms === 60000));
  console.log('Market tests PASS: two real observations, three series, request deduplication, stale/unvalidated rejection, USD failure fallback, stale-display state, 60s timer.');
  dom.window.close();
})().catch(e => { console.error(e); dom.window.close(); process.exitCode = 1; });
